baseURL = "https://www.radioactive-mutant-vampire-zombie-robots-from-outerspace.de/"
languageCode = "en-us"
title = "What if radioactive mutant vampire zombie robots from outerspace attack?!"
theme = "hello-friend-ng"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
enableThemeToggle = true

[params.logo]
  logoMark     = ">>"
  logoText     = "rmvzrfo"
  logoHomeLink = "/"
  logoCursorDisabled = true
